import type { DiagnosticRegistryEntry } from '@/lib/admin/diagnostics/v4/types'

export const INGESTION_DIAGNOSTICS_REGISTRY: readonly DiagnosticRegistryEntry[] = [
  {
    id: 'duplicate_canonical_clusters',
    displayName: 'Duplicate canonical publish clusters',
    description: 'Canonical keys mapping to more than one published_sale_id',
    operationalDomain: 'duplicate_detection',
    owner: 'manual review',
    operational: true,
    sloParticipation: true,
    blockingSlo: true,
    exportModes: ['operations', 'engineering', 'full'],
    runbookReference: 'docs/YSTM_HANDS_OFF_STEADY_STATE_PROGRAM.md',
  },
  {
    id: 'duplicate_convergence_streak',
    displayName: 'Duplicate convergence streak',
    description: 'Consecutive UTC days at zero duplicate canonical clusters',
    operationalDomain: 'duplicate_detection',
    owner: 'duplicate-canonical-slo cron',
    operational: true,
    sloParticipation: true,
    blockingSlo: false,
    exportModes: ['operations', 'engineering', 'full'],
    runbookReference: null,
  },
  {
    id: 'parser_success_24h',
    displayName: 'Parser success (24h)',
    description: 'Detail-first ready rate on 24h funnel cohort',
    operationalDomain: 'parsing',
    owner: 'parser',
    operational: true,
    sloParticipation: true,
    blockingSlo: true,
    exportModes: ['operations', 'engineering', 'full'],
    runbookReference: null,
  },
  {
    id: 'coverage_pct',
    displayName: 'Coverage',
    description: 'Nationwide YSTM footprint coverage percentage',
    operationalDomain: 'visibility_coverage',
    owner: 'coverage audit',
    operational: true,
    sloParticipation: true,
    blockingSlo: false,
    exportModes: ['operations', 'engineering', 'full'],
    runbookReference: null,
  },
  {
    id: 'catalog_repair_queue',
    displayName: 'Catalog repair queue',
    description: 'Rows awaiting catalog repair drain',
    operationalDomain: 'catalog_repair',
    owner: 'catalog-repair cron',
    operational: true,
    sloParticipation: true,
    blockingSlo: false,
    exportModes: ['operations', 'engineering', 'full'],
    runbookReference: 'docs/YSTM_REFRESH_AND_NEEDS_CHECK_RUNBOOK.md',
  },
  {
    id: 'publish_failed_terminal',
    displayName: 'Terminal publish_failed',
    description: 'Ingested rows in terminal publish_failed status',
    operationalDomain: 'publishing',
    owner: 'publish worker',
    operational: true,
    sloParticipation: true,
    blockingSlo: true,
    exportModes: ['operations', 'engineering', 'full'],
    runbookReference: null,
  },
  {
    id: 'canonical_key_coverage',
    displayName: 'Canonical key coverage',
    description: 'Active external rows with canonical_sale_instance_key',
    operationalDomain: 'data_quality',
    owner: 'canonical backfill',
    operational: true,
    sloParticipation: true,
    blockingSlo: false,
    exportModes: ['operations', 'engineering', 'full'],
    runbookReference: null,
  },
  {
    id: 'actionable_missing_valid',
    displayName: 'Actionable missing valid URLs',
    description: 'Reconciled missing valid URLs requiring operator action',
    operationalDomain: 'visibility_coverage',
    owner: 'missing-ingest cron',
    operational: true,
    sloParticipation: true,
    blockingSlo: false,
    exportModes: ['operations', 'engineering', 'full'],
    runbookReference: null,
  },
  {
    id: 'observation_stale',
    displayName: 'Observation stale',
    description: 'Published sales visible but coverage observation stale',
    operationalDomain: 'visibility_coverage',
    owner: 'observation refresh',
    operational: true,
    sloParticipation: false,
    blockingSlo: false,
    exportModes: ['engineering', 'full'],
    runbookReference: null,
  },
  {
    id: 'visible_duplicate_clusters',
    displayName: 'Visible duplicate clusters',
    description: 'Duplicate visible address+date clusters vs published active',
    operationalDomain: 'duplicate_detection',
    owner: 'manual review',
    operational: true,
    sloParticipation: false,
    blockingSlo: false,
    exportModes: ['engineering', 'full'],
    runbookReference: null,
  },
  {
    id: 'seo_readiness',
    displayName: 'SEO readiness',
    description: 'SEO product enablement gate (separate from ingestion health)',
    operationalDomain: 'visibility_coverage',
    owner: 'seo ops',
    operational: false,
    sloParticipation: false,
    blockingSlo: false,
    exportModes: ['engineering', 'full'],
    runbookReference: 'docs/SEO_FINAL_DEVELOPMENT_SPEC.md',
  },
  {
    id: 'rollout_gates',
    displayName: 'Sale instance rollout gates',
    description: 'Phase 14 convergence and enforcement readiness',
    operationalDomain: 'engineering',
    owner: 'engineering',
    operational: false,
    sloParticipation: false,
    blockingSlo: false,
    exportModes: ['full'],
    runbookReference: null,
  },
] as const

export function getRegistryEntry(id: string): DiagnosticRegistryEntry | undefined {
  return INGESTION_DIAGNOSTICS_REGISTRY.find((entry) => entry.id === id)
}
