export type YstmStrategicMetroRegistryEntry = {
  slug: string
  configId: string
  city: string
  state: string
  principalPageUrl: string
  refreshTargetHours: number
}

/** Production-validated Tier 1 strategic metros (39 APPROVED; Denver excluded). */
export const YSTM_STRATEGIC_METRO_REGISTRY_V1: readonly YstmStrategicMetroRegistryEntry[] = [
  {
    slug: 'atlanta-ga',
    configId: '9b7f4b98-d955-4849-a7d0-b9f553d791bc',
    city: 'Atlanta',
    state: 'GA',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/Georgia/Atlanta.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'austin-tx',
    configId: 'f7191721-343f-40f5-9185-927c3bf8010b',
    city: 'Austin',
    state: 'TX',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/Texas/Austin.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'baltimore-md',
    configId: '3397c87a-e0b8-4fe1-94bd-b7a7873dab83',
    city: 'Baltimore',
    state: 'MD',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/Maryland/Baltimore.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'boston-ma',
    configId: '4eae836b-3d0d-4d9c-9edd-2aeaec116816',
    city: 'Boston',
    state: 'MA',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/Massachusetts/Boston.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'charlotte-nc',
    configId: '36acf5ce-9d6a-4b06-8133-459eaaee82cf',
    city: 'Charlotte',
    state: 'NC',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/North-Carolina/Charlotte.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'chicago-il',
    configId: 'df49b588-4711-4518-a26c-f5c4d38786e4',
    city: 'Chicago',
    state: 'IL',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/Illinois/Chicago.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'cincinnati-oh',
    configId: '42f19c66-5d43-492d-8c24-a57e72e64492',
    city: 'Cincinnati',
    state: 'OH',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/Ohio/Cincinnati.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'columbus-oh',
    configId: '3439f2bd-21d3-4bf7-b60f-2943adfba8e0',
    city: 'Columbus',
    state: 'OH',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/Ohio/Columbus.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'dallas-tx',
    configId: '736117c8-f15f-4026-b076-d4da13666493',
    city: 'Dallas',
    state: 'TX',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/Texas/Dallas.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'detroit-mi',
    configId: '15355077-1c76-4c52-8b32-5608e0b1b548',
    city: 'Detroit',
    state: 'MI',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/Michigan/Detroit.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'houston-tx',
    configId: '5a89eb0f-fbb2-4429-a4f4-b419eaf0f5a7',
    city: 'Houston',
    state: 'TX',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/Texas/Houston.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'indianapolis-in',
    configId: 'd7d1e26d-8437-4fc3-8cff-33c0f2e8a3f8',
    city: 'Indianapolis',
    state: 'IN',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/Indiana/Indianapolis.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'jacksonville-fl',
    configId: '878c1ab0-fe7a-4b55-abd7-2959ddc046db',
    city: 'Jacksonville',
    state: 'FL',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/Florida/Jacksonville.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'kansas-city-mo',
    configId: '77170ce0-e4e2-4ee0-84bf-e109f987afa3',
    city: 'Kansas City',
    state: 'MO',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/Missouri/Kansas-City.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'las-vegas-nv',
    configId: 'fee06a8f-07ab-46f2-88bc-1fda16fabaed',
    city: 'Las Vegas',
    state: 'NV',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/Nevada/Las-Vegas.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'los-angeles-ca',
    configId: '94ae2d1c-bd89-467c-a2fe-1f6db6816ead',
    city: 'Los Angeles',
    state: 'CA',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/California/Los-Angeles.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'louisville-ky',
    configId: '4f205b24-9010-4248-a17e-5d47e0cc74e4',
    city: 'Louisville',
    state: 'KY',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/Kentucky/Louisville.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'memphis-tn',
    configId: '9bedce9b-23d0-45f9-9e28-ef3ff9e90fc7',
    city: 'Memphis',
    state: 'TN',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/Tennessee/Memphis.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'miami-fl',
    configId: '24e6c1c3-1085-4cd3-9004-e652711b6a49',
    city: 'Miami',
    state: 'FL',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/Florida/Miami.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'minneapolis-mn',
    configId: '01a9c370-e115-43b5-928e-b929cfe96f30',
    city: 'Minneapolis',
    state: 'MN',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/Minnesota/Minneapolis.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'nashville-tn',
    configId: '9ff3dda1-6a78-46dd-8e63-2a635f7ea374',
    city: 'Nashville',
    state: 'TN',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/Tennessee/Nashville.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'new-orleans-la',
    configId: '5b70e36a-2fef-476d-a942-18b12e2ca1b2',
    city: 'New Orleans',
    state: 'LA',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/Louisiana/New-Orleans.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'new-york-city-ny',
    configId: '0ef0daf0-55a4-49dc-84e7-6c49e204d385',
    city: 'New York City',
    state: 'NY',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/New-York/New-York-City.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'oklahoma-city-ok',
    configId: 'f3bce4b2-4567-4e72-97c8-6208f106234b',
    city: 'Oklahoma City',
    state: 'OK',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/Oklahoma/Oklahoma-City.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'orlando-fl',
    configId: '9201a2ce-f082-4af0-8f09-44f68aba19ce',
    city: 'Orlando',
    state: 'FL',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/Florida/Orlando.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'philadelphia-pa',
    configId: '67eed732-813f-47e1-bfea-dca32bd5be79',
    city: 'Philadelphia',
    state: 'PA',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/Pennsylvania/Philadelphia.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'phoenix-az',
    configId: '8ec56a41-4c4c-4de2-942e-480495467baa',
    city: 'Phoenix',
    state: 'AZ',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/Arizona/Phoenix.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'pittsburgh-pa',
    configId: 'd3b5f084-724f-46fe-9c61-d2cb5915c69a',
    city: 'Pittsburgh',
    state: 'PA',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/Pennsylvania/Pittsburgh.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'portland-or',
    configId: '3f147340-ccc1-49b2-8040-a36018755543',
    city: 'Portland',
    state: 'OR',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/Oregon/Portland.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'raleigh-nc',
    configId: '4ebfbf15-137e-4d6c-876d-b9207059039a',
    city: 'Raleigh',
    state: 'NC',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/North-Carolina/Raleigh.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'riverside-ca',
    configId: '063d28c1-befa-43e1-b2b3-ea164d2fc7be',
    city: 'Riverside',
    state: 'CA',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/California/Riverside.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'sacramento-ca',
    configId: '6b821ece-efd1-4662-8bd8-e8e3798331cf',
    city: 'Sacramento',
    state: 'CA',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/California/Sacramento.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'saint-louis-mo',
    configId: '5304b932-2f40-4942-8a80-6d534326b93a',
    city: 'Saint Louis',
    state: 'MO',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/Missouri/Saint-Louis.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'san-antonio-tx',
    configId: 'f7ec4a7c-8068-4a46-b3be-ebc35df24ed8',
    city: 'San Antonio',
    state: 'TX',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/Texas/San-Antonio.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'san-diego-ca',
    configId: '370efbfe-6575-4a74-8c2b-04f0578b1476',
    city: 'San Diego',
    state: 'CA',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/California/San-Diego.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'san-francisco-ca',
    configId: '1a4b4821-cc31-40c9-a3d0-5be1533a581c',
    city: 'San Francisco',
    state: 'CA',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/California/San-Francisco.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'seattle-wa',
    configId: 'f9711560-e647-4519-8483-ee4ad2160c1b',
    city: 'Seattle',
    state: 'WA',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/Washington/Seattle.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'tampa-fl',
    configId: '7a164ca5-f1aa-49d3-87a0-9ccf50bd72ee',
    city: 'Tampa',
    state: 'FL',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/Florida/Tampa.html',
    refreshTargetHours: 2,
  },
  {
    slug: 'washington-dc',
    configId: 'c1a77c31-5b5d-4510-b5db-241dcb18e81d',
    city: 'Washington',
    state: 'DC',
    principalPageUrl: 'https://yardsaletreasuremap.com/US/District-of-Columbia/Washington.html',
    refreshTargetHours: 2,
  },
] as const
