name = "lootaura-ingest-proxy"
main = "src/index.ts"
account_id = "064c6c721b9e45dbb4bc2cf325aca042"
compatibility_date = "2025-09-26"

# Cron can be configured via secrets.CRON_SCHEDULE or in Cloudflare UI
# schedules = ["0 */6 * * *"]


