export type Badge = {
  name: string
  href: string
  img: string
  addedAt: string
  requirement: "badge"
}

export const BADGES: Badge[] = [
  {
    name: "Million Dot Homepage",
    href: "https://milliondothomepage.com/product/loot-aura",
    img: "https://milliondothomepage.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Fazier badge",
    href: "https://fazier.com/launches/lootaura.com",
    img: "https://fazier.com/api/v1//public/badges/launch_badges.svg?badge_type=launched&theme=neutral",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Featured on Twelve Tools",
    href: "https://twelve.tools",
    img: "https://twelve.tools/badge0-white.svg",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Featured on SaaSBison",
    href: "https://saasbison.com",
    img: "https://saasbison.com/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Launched on LaunchPanda",
    href: "https://launchpanda.dev/launches",
    img: "https://launchpanda.dev/images/badges/launchpanda-badge.svg",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Unite List",
    href: "https://unitelist.com",
    img: "https://unitelist.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Featured on Toolfio",
    href: "https://toolfio.com",
    img: "https://toolfio.com/toolfio-light-badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Featured on ufind.best",
    href: "https://ufind.best/products/loot-aura?utm_source=ufind.best",
    img: "https://ufind.best/badges/ufind-best-badge-light.svg",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Acid Tools",
    href: "https://acidtools.com",
    img: "https://acidtools.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Featured on neeed.directory",
    href: "https://neeed.directory/products/lootaura?utm_source=lootaura",
    img: "https://neeed.directory/badges/neeed-badge-light.svg",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Featured on Wired Business",
    href: "https://wired.business",
    img: "https://wired.business/badge0-white.svg",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "My Launch Stash",
    href: "https://mylaunchstash.com",
    img: "https://mylaunchstash.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Startup Vessel",
    href: "https://startupvessel.com",
    img: "https://startupvessel.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Startup Benchmarks",
    href: "https://startupbenchmarks.com",
    img: "https://startupbenchmarks.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Loot Aura badge",
    href: "https://www.proofstories.io/directory/products/loot-aura/",
    img: "https://www.proofstories.io/directory/badges/l/loot-aura.svg",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Featured on FoundrList",
    href: "https://www.foundrlist.com/product/lootaura-2?utm_source=badge&utm_medium=embed",
    img: "https://www.foundrlist.com/api/badge/lootaura-2",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Tool Dynamo",
    href: "https://tooldynamo.com",
    img: "https://tooldynamo.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Tool Ignite",
    href: "https://toolignite.com",
    img: "https://toolignite.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Toolkit Index",
    href: "https://toolkitindex.com",
    img: "https://toolkitindex.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Tool Networker",
    href: "https://toolnetworker.com",
    img: "https://toolnetworker.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Tool Parade",
    href: "https://toolparade.com",
    img: "https://toolparade.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Good AI Tools",
    href: "https://goodaitools.com/ai/loot-aura",
    img: "https://goodaitools.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Featured on Submit Your Product - LaunchClash",
    href: "https://launchclash.com/product/loot-aura",
    img: "https://launchclash.com/static/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "AIGC 160",
    href: "https://aigc160.com",
    img: "https://aigc160.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "AI X Collection",
    href: "https://aixcollection.com",
    img: "https://aixcollection.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Appa List",
    href: "https://appalist.com",
    img: "https://appalist.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Appsy Tools",
    href: "https://appsytools.com",
    img: "https://appsytools.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Ash List",
    href: "https://ashlist.com",
    img: "https://ashlist.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Beam Tools",
    href: "https://beamtools.com",
    img: "https://beamtools.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Best Tool Vault",
    href: "https://besttoolvault.com",
    img: "https://besttoolvault.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Hunt for Tools",
    href: "https://huntfortools.com",
    img: "https://huntfortools.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Latest AI Updates",
    href: "https://latestaiupdates.com",
    img: "https://latestaiupdates.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Launch Scroll",
    href: "https://launchscroll.com",
    img: "https://launchscroll.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "My Start Tools",
    href: "https://mystarttools.com",
    img: "https://mystarttools.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Power Up Tools",
    href: "https://poweruptools.com",
    img: "https://poweruptools.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Product List Dir",
    href: "https://productlistdir.com",
    img: "https://productlistdir.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Product Wing",
    href: "https://productwing.com",
    img: "https://productwing.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "SaaS Field",
    href: "https://saasfield.com",
    img: "https://saasfield.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "SaaS Hub Directory",
    href: "https://saashubdirectory.com",
    img: "https://saashubdirectory.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "SaaS Roots",
    href: "https://saasroots.com",
    img: "https://saasroots.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "SaaS Tools Dir",
    href: "https://saastoolsdir.com",
    img: "https://saastoolsdir.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "SaaS Wheel",
    href: "https://saaswheel.com",
    img: "https://saaswheel.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Smart Kit Hub",
    href: "https://smartkithub.com",
    img: "https://smartkithub.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Software Bolt",
    href: "https://softwarebolt.com",
    img: "https://softwarebolt.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Solver Tools",
    href: "https://solvertools.com",
    img: "https://solvertools.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Source Dir",
    href: "https://sourcedir.com",
    img: "https://sourcedir.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Stack Directory",
    href: "https://stackdirectory.com",
    img: "https://stackdirectory.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Super AI Boom",
    href: "https://superaiboom.com",
    img: "https://superaiboom.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "That App Show",
    href: "https://thatappshow.com",
    img: "https://thatappshow.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "The App Tools",
    href: "https://theapptools.com",
    img: "https://theapptools.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "The Core Tools",
    href: "https://thecoretools.com",
    img: "https://thecoretools.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "The Key Tools",
    href: "https://thekeytools.com",
    img: "https://thekeytools.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "The Mega Tools",
    href: "https://themegatools.com",
    img: "https://themegatools.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Tiny Tool Hub",
    href: "https://tinytoolhub.com",
    img: "https://tinytoolhub.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Tool Cosmos",
    href: "https://toolcosmos.com",
    img: "https://toolcosmos.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Tool Find Dir",
    href: "https://toolfinddir.com",
    img: "https://toolfinddir.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Tool Journey",
    href: "https://tooljourney.com",
    img: "https://tooljourney.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Tool Prism",
    href: "https://toolprism.com",
    img: "https://toolprism.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Tool Signal",
    href: "https://toolsignal.com",
    img: "https://toolsignal.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Tools List HQ",
    href: "https://toolslisthq.com",
    img: "https://toolslisthq.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Tools Under Radar",
    href: "https://toolsunderradar.com",
    img: "https://toolsunderradar.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Top Trend Tools",
    href: "https://toptrendtools.com",
    img: "https://toptrendtools.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Toshi List",
    href: "https://toshilist.com",
    img: "https://toshilist.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "Trustiner",
    href: "https://trustiner.com",
    img: "https://trustiner.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
  {
    name: "We Like Tools",
    href: "https://weliketools.com",
    img: "https://weliketools.com/assets/images/badge.png",
    addedAt: "2026-04-20",
    requirement: "badge",
  },
]
