/** Fixed pixel type scale for 1080×1350 instagram-feed canvas (template parity). */
export const SOCIAL_REPORT_INSTAGRAM_TYPOGRAPHY = {
  brandPinHeightPx: 44,
  brandNamePx: 24,
  brandTaglinePx: 11,
  cityTitlePx: 76,
  weekendReportPx: 26,
  dateLinePx: 16,
  rankNumberPx: 64,
  rankTrophyPx: 40,
  rankCaptionPx: 11,
  heroMetricValuePx: 88,
  heroMetricLabelPx: 22,
  heroMetricSubtitlePx: 16,
  heroMetricIconBadgePx: 80,
  heroMetricIconPx: 40,
  secondaryMetricValuePx: 64,
  secondaryMetricLabelPx: 16,
  secondaryMetricIconBadgePx: 64,
  secondaryMetricIconPx: 32,
} as const
