/** Fixed pixel type scale for 1080×1350 instagram-feed canvas (template parity). */
export const SOCIAL_REPORT_INSTAGRAM_TYPOGRAPHY = {
  brandPinHeightPx: 50,
  brandNamePx: 30,
  brandTaglinePx: 14,
  cityTitlePx: 76,
  weekendReportPx: 34,
  dateLinePx: 20,
  rankNumberPx: 64,
  rankTrophyPx: 40,
  rankCaptionPx: 11,
  heroMetricValuePx: 88,
  heroMetricLabelPx: 28,
  heroMetricSubtitlePx: 20,
  heroMetricIconBadgePx: 80,
  heroMetricIconPx: 40,
  secondaryMetricValuePx: 64,
  secondaryMetricLabelPx: 22,
  secondaryMetricIconBadgePx: 64,
  secondaryMetricIconPx: 32,
} as const
