name: Deploy Cloudflare Worker (ingest-proxy)

on:
  push:
    branches:
      - feat/ingest-stabilization
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Wrangler
        run: npm install -g wrangler@3

      - name: Configure Worker Secrets
        working-directory: workers/ingest-proxy
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          POST_URL: ${{ secrets.POST_URL }}
          INGEST_TOKEN: ${{ secrets.INGEST_TOKEN }}
          SITES: ${{ secrets.SITES }}
          USER_AGENT: ${{ secrets.USER_AGENT }}
          CRON_SCHEDULE: ${{ secrets.CRON_SCHEDULE }}
        run: |
          echo "Setting secrets"
          echo -n "$POST_URL" | wrangler secret put POST_URL --quiet
          echo -n "$INGEST_TOKEN" | wrangler secret put INGEST_TOKEN --quiet
          echo -n "$SITES" | wrangler secret put SITES --quiet
          echo -n "$USER_AGENT" | wrangler secret put USER_AGENT --quiet
          if [ -n "$CRON_SCHEDULE" ]; then
            echo "Adding cron to wrangler.toml"
            echo "\nschedules = [\"$CRON_SCHEDULE\"]" >> wrangler.toml
          fi

      - name: Publish Worker
        working-directory: workers/ingest-proxy
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: wrangler deploy


