name: Update STATUS

on:
  push:
    branches:
      - main
      - 'milestone/**'
  workflow_dispatch: {}

jobs:
  update-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Generate STATUS.md
        run: npx tsx scripts/update-status.ts

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add STATUS.md
          if git diff --cached --quiet; then
            echo "No changes to commit"; exit 0; fi
          git commit -m "chore(status): auto-update STATUS.md"

      - name: Push
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
