name: YSF Step B
on:
  workflow_dispatch:

jobs:
  b:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Prepare branch
        run: |
          git config user.name "lanternetbot"
          git config user.email "bot@example.com"
          git checkout -b ysf-step-b-${GITHUB_RUN_ID}
      - name: Add a file
        run: |
          mkdir -p lib
          printf "export const ok=true;\n" > lib/ok.ts
          git add -A
          git commit -m "chore: step B smoke"
      - name: Push
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          git push https://x-access-token:${BOT_TOKEN}@github.com/lanternetwork/YardSaleTracker.git HEAD:ysf-step-b-${GITHUB_RUN_ID}
      - name: Open PR
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          echo '{ "title":"Step B: smoke", "head":"ysf-step-b-'${GITHUB_RUN_ID}'", "base":"main", "body":"Smoke PR before full Step B." }' > pr.json
          curl -s -X POST \
            -H "Authorization: token ${BOT_TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/lanternetwork/YardSaleTracker/pulls \
            -d @pr.json
