name: YSF Step B
on:
  workflow_dispatch:

jobs:
  step_b:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Create branch
        run: |
          git config user.name lanternetbot
          git config user.email bot@example.com
          git checkout -b ysf-step-b-${GITHUB_RUN_ID}

      - name: Add minimal Step B file
        run: |
          mkdir -p lib
          echo "export const ok = true;" > lib/ok.ts
          git add -A
          git commit -m "chore: step B smoke"

      - name: Push branch
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          git push https://x-access-token:${BOT_TOKEN}@github.com/lanternetwork/YardSaleTracker.git HEAD:ysf-step-b-${GITHUB_RUN_ID}
